config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'jobs/indexall'

  resources :posts
  resources :companies
  resources :jobs do
      member do
          put 'like', to: "jobs#upvote"
          get 'like'
    end

end

  resources :conversations do
    resources :messages
  end
  resources :searches
  resources :finds
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :profiles

  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"

   get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"

   resources :resumes, only: [:index, :new, :create, :destroy]

   root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :name, :description, uniqueness: { scope: :name, message: "company already exists!" }
  validates :name, :description, presence: true
end

app/models/find.rb
class Find < ActiveRecord::Base
  def find_names
      users = User.all
      users = users.where(["first_name LIKE?",first_name]) if first_name.present?
      users = users.where(["last_name LIKE?",last_name]) if last_name.present?
      return users
    end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
    acts_as_votable
    acts_as_voter
    has_many :like, dependent: :destroy
    has_many :liked_users, through: :like, source: :user
	include PublicActivity::Model
	tracked

	def self.search(search)
			if search
				where(["company LIKE ?", "%#{search}%"])
			else
				all
			end
		end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
	include PublicActivity::Model
	tracked
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	##Image Uploading
	  mount_uploader :avatar, AvatarUploader

		belongs_to :user
    validates_associated :user

	def self.search(search)

			if search
				where(["occupation LIKE ?", "%#{search}%"])
			else
				all
			end
		end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   belongs_to :user
end

app/models/search.rb
class Search < ActiveRecord::Base


		def find_jobs
			
			jobs = Job.all

			jobs = jobs.where(["company LIKE?", company ]) if company.present?
			jobs = jobs.where(["title LIKE?", title  ]) if title.present?
			jobs = jobs.where(["description LIKE?", description ]) if description.present?

			return jobs
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
acts_as_voter
has_many :jobs
has_many :like, dependent: :destroy
has_many :liked_votes, through: :like, source: :jobs
has_many :posts
has_many :resumes
has_one :profile
before_create :build_profile
has_many :friendships
has_many :friends, :through => :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user
has_one :company

acts_as_messageable

def name
	"User #{id}"
end

def mailboxer_email(object)
	nil
end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :job
    #validates_uniqueness_of :vote_id, scope: :user_id
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	def index
		@conversations = current_user.mailbox.conversations.order('created_at DESC')
	end

	def show
		@conversation = current_user.mailbox.conversations.find(params[:id])
	end

	def new
		@recipients = [User.find(params[:user])]
	end

	def create
		recipient = User.find(params[:user_id])
		receipt = current_user.send_message(recipient, params[:body], params[:subject])
		redirect_to conversation_path(receipt.conversation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/finds_helper.rb
module FindsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/index.html.erb
<div class="col-sm-6 col-md-offset-3">
<h1>All Conversation </h1>

	<% @conversations.each do |conversation| %>
	<div style="background-color:#F0F8FF;">
	<h3 style="background-color:white;">	<%= link_to conversation.subject, conversation_path(conversation) %></h3>
	<%= time_ago_in_words(conversation.created_at) %> ago

	</div>
<br><% end %>
</div>

app/views/conversations/new.html.erb
<div style="background-color:#F0F8FF;">
<h1> New Message </h1>
<%= form_tag conversations_path, method: :post do %>
	<div>
		<%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :email) %>

	</div>

	<div>
		<%= text_field_tag :subject, nil, placeholder: "Subject" %>
	</div>

	<div>
		<%= text_area_tag :body, nil, placeholder: "Send a message" %>
	</div>

	<%= submit_tag "Send message" %>
	<% end %>
</div>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %> </h1>
<div class="col-sm-6 col-md-offset-3">
<% @conversation.receipts_for(current_user).each do |receipt| %>
	<div>
		<div id="jobbox" style="background-color:#F0F8FF; margin-bottom: 15px;">
		    <h5 style="background-color: #F0F8FF;">
		<% unless receipt.message.sender.profile.avatar_url.nil? %>
	 <img src="<%=receipt.message.sender.profile.avatar_url(:thumbnail)%>">
			 <% else %>
				 <img src="/assets/defaultprofile" height=50px width=50px>
			 <% end %>
		<span><%= receipt.message.sender.first_name %> </span></h5>
			<p style="background-color: white;"><%= receipt.message.body %> </p>
			<p style="background-color: white;">Posted <%= time_ago_in_words(receipt.message.created_at) %> ago</p>
		</div>
	</div>
	<% end %>

	<%= form_tag conversation_messages_path(@conversation), method: :post do %>
	<div>
		<%= text_area_tag :body %>
	</div>

	<%= submit_tag "Send messages" %>
	<% end %>
</div>