config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'jobs/indexall'

  resources :posts
  resources :companies
  resources :jobs do
      member do
          put 'like', to: "jobs#upvote"
          get 'like'
    end

end

  resources :conversations do
    resources :messages
  end
  resources :searches
  resources :finds
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :profiles

  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"

   get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"

   resources :resumes, only: [:index, :new, :create, :destroy]

   root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :name, :description, uniqueness: { scope: :name, message: "company already exists!" }
  validates :name, :description, presence: true
end

app/models/find.rb
class Find < ActiveRecord::Base
  def find_names
      users = User.all
      users = users.where(["first_name LIKE?",first_name]) if first_name.present?
      users = users.where(["last_name LIKE?",last_name]) if last_name.present?
      return users
    end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
    acts_as_votable
    acts_as_voter
    has_many :like, dependent: :destroy
    has_many :liked_users, through: :like, source: :user
	include PublicActivity::Model
	tracked

	def self.search(search)
			if search
				where(["company LIKE ?", "%#{search}%"])
			else
				all
			end
		end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
	include PublicActivity::Model
	tracked
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	##Image Uploading
	  mount_uploader :avatar, AvatarUploader

		belongs_to :user
    validates_associated :user

	def self.search(search)

			if search
				where(["occupation LIKE ?", "%#{search}%"])
			else
				all
			end
		end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   belongs_to :user
end

app/models/search.rb
class Search < ActiveRecord::Base


		def find_jobs
			
			jobs = Job.all

			jobs = jobs.where(["company LIKE?", company ]) if company.present?
			jobs = jobs.where(["title LIKE?", title  ]) if title.present?
			jobs = jobs.where(["description LIKE?", description ]) if description.present?

			return jobs
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
acts_as_voter
has_many :jobs
has_many :like, dependent: :destroy
has_many :liked_votes, through: :like, source: :jobs
has_many :posts
has_many :resumes
has_one :profile
before_create :build_profile
has_many :friendships
has_many :friends, :through => :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user
has_one :company

acts_as_messageable

def name
	"User #{id}"
end

def mailboxer_email(object)
	nil
end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :job
    #validates_uniqueness_of :vote_id, scope: :user_id
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_filter :authenticate_user!

  def index
    @user = current_user
    @post = Post.new
    @jobs = Job.order('created_at DESC')
    @activities = PublicActivity::Activity.order('created_at DESC')
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :load_activities, only: [:index, :show, :new, :edit, :upvote]
  before_filter :authenticate_user!, :getUser
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.where(["name LIKE ?","%#{params[:search]}%"])
    @activities = Job.all.order('created_at DESC')
    #PublicActivity::Activity.order('created_at DESC')
    @user = current_user
    #@jobs = @user.jobs


  end

  def indexall
    @jobs = Job.all.order('created_at DESC')
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_url }
        format.json { render :index, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully delted.' }
      format.json { head :no_content }
    end
  end


  def upvote
      @job = Job.find(params[:id])
      @job.liked_by current_user
      respond_to do |format|
          format.html {redirect_to :back }
          format.json
      end
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :title, :description)
    end

    def getUser
      @user = current_user
    end

    def load_activities
  @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/finds_helper.rb
module FindsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<head>
<style>



</style>
</head>

<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company  %>
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div style="background-color: white;">
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<div class="col-sm-6 col-md-offset-3">
 <% if current_user.premium  %>
  <h1 align="center">Your Jobs</h1>
  <p><%= link_to 'All Jobs', jobs_indexall_path %> </p>
  <%= link_to "New Job", new_job_path, :method => :get %>
  <p><%= link_to 'Search Jobs', new_search_path %> </p>
  <br>
  <% @user = current_user %>
  <% @user.jobs.order('created_at DESC').each do |a| %>
  <div id="jobbox" style="background-color:#F0F8FF; margin-bottom: 15px;">
    <h2 style="background-color: #F0F8FF;">
      <%= link_to a.company, job_path(a) %></h2>
    <div id="jobtitle" style="background-color: white;">
      <h6> Job Title </h6>
      <div style="border: solid 1px; height: 50px" >
        <%= a.title %>
      </div>
      <h6> Description </h6>
      <div style="border: solid 1px; height: 80px">
        <%= a.description %>
      </div>
      <%= link_to like_job_path(a), method: :put do%>
      Liked
      <%= a.get_upvotes.size %>

      <% end %>
      </div>
      </div>
      <%end %>
      <% end %>


<% if !current_user.premium %>
  <h1 align="center" >Liked Jobs</h1>
  <p><%= link_to 'All Jobs', jobs_indexall_path %> </p>
      <p><%= link_to 'Search Jobs', new_search_path %> </p>
      <% @user.find_voted_items.each do |a| %>
      <div id="jobbox" style="background-color:#F0F8FF; margin-bottom: 15px;">
        <h2 style="background-color: #F0F8FF;">
          <%= a.company%></h2>
        <div id="jobtitle" style="background-color: white;">
          <h6> Job Title </h6>
          <div style="border: solid 1px; height: 50px" >
            <%= a.title %>
          </div>
          <h6> Description </h6>
          <div style="border: solid 1px; height: 80px">
            <%= a.description %>
          </div>
          <%= link_to like_job_path(a), method: :put do%>
          Liked
          <%= a.get_upvotes.size %>

          <% end %>
          </div>
          </div>
          <%end %>
          <% end %>
        </div>

app/views/jobs/indexall.html.erb
<div class="col-sm-6 col-md-offset-3">
  <h1 align="center">All Jobs</h1>
  <% if current_user.premium %>
  <p><%= link_to 'My Jobs', jobs_path %> </p>
    <%= link_to "New Job", new_job_path, :method => :get %>
  <% else %>
  <p><%= link_to 'Liked Jobs', jobs_path %> </p>
  <% end %>
  <p><%= link_to 'Search Jobs', new_search_path %> </p>
  <br>
<% @jobs.each do |a| %>
<div id="jobbox" style="background-color:#F0F8FF; margin-bottom: 15px;">
  <h2 style="background-color: #F0F8FF;">
    <%= a.company%></h2>
  <div id="jobtitle" style="background-color: white;">
    <h6> Job Title </h6>
    <div style="border: solid 1px; height: 50px" >
      <%= a.title %>
    </div>
    <h6> Description </h6>
    <div style="border: solid 1px; height: 80px">
      <%= a.description %>
    </div>
    <%= link_to like_job_path(a), method: :put do%>
    Like
    <%= a.get_upvotes.size %>

    <% end %>
    <button type="button" class="btn btn-link"
    id = "jobbox" onclick="myFunction()">Skip</button>
    <script>
    function myFunction() {
      $('#jobbox').remove();
        //document.getElementById("jobbox").style.display='none';
    }
    </script>
    </div>
    </div>
    <%end %>
  </div>

app/views/jobs/new.html.erb
<div style="background-color: white;">
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<div style="background-color: white;">
<p>
  <strong><%= @job.title %></strong>
</p>
<table style="width:100%; border-collapse: separate; border-spacing: 0px 10px">
  <thead style="font-size: 20px; border: 1px solid black">
    <tr>
      <th>Candidate Name</th>
      <th>Occupation</th>
      <th>Resume</th>
      <th> </th>

      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
    <% @job.votes_for.up.by_type(User).voters.each do |user| %>
      <tr>
        <td><%= user.first_name + " " + user.last_name %></td>
        <td>
          <% if user.profile.occupation %>
          <%= user.profile.occupation %>
        <%else%>
        Not Available
        <% end %>
      </td>
        <td>
          <% if user.resumes.first %>
          <%= link_to "Download Resume", user.resumes.first.attachment_url %>
        <% else%>
        Not Available
        <% end %>
      </td>

        <td><button type="button" class="btn btn-link"style="margin-right:-30px"
        value = "voters" onclick="myFunction(this)">Skip</button>
        <script>
        function myFunction(e) {

          $(e).closest('tr').remove();
            //document.getElementById("jobbox").style.display='none';
        }
        </script>

        </td>
        <td>
          <%= link_to "Message".html_safe, new_conversation_path(:user => user)  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>
</div>