config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'jobs/indexall'

  resources :posts
  resources :companies
  resources :jobs do
      member do
          put 'like', to: "jobs#upvote"
          get 'like'
    end

end

  resources :conversations do
    resources :messages
  end
  resources :searches
  resources :finds
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :profiles

  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"

   get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"

   resources :resumes, only: [:index, :new, :create, :destroy]

   root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :name, :description, uniqueness: { scope: :name, message: "company already exists!" }
  validates :name, :description, presence: true
end

app/models/find.rb
class Find < ActiveRecord::Base
  def find_names
      users = User.all
      users = users.where(["first_name LIKE?",first_name]) if first_name.present?
      users = users.where(["last_name LIKE?",last_name]) if last_name.present?
      return users
    end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
    acts_as_votable
    acts_as_voter
    has_many :like, dependent: :destroy
    has_many :liked_users, through: :like, source: :user
	include PublicActivity::Model
	tracked

	def self.search(search)
			if search
				where(["company LIKE ?", "%#{search}%"])
			else
				all
			end
		end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
	include PublicActivity::Model
	tracked
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	##Image Uploading
	  mount_uploader :avatar, AvatarUploader

		belongs_to :user
    validates_associated :user

	def self.search(search)

			if search
				where(["occupation LIKE ?", "%#{search}%"])
			else
				all
			end
		end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   belongs_to :user
end

app/models/search.rb
class Search < ActiveRecord::Base


		def find_jobs
			
			jobs = Job.all

			jobs = jobs.where(["company LIKE?", company ]) if company.present?
			jobs = jobs.where(["title LIKE?", title  ]) if title.present?
			jobs = jobs.where(["description LIKE?", description ]) if description.present?

			return jobs
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
acts_as_voter
has_many :jobs
has_many :like, dependent: :destroy
has_many :liked_votes, through: :like, source: :jobs
has_many :posts
has_many :resumes
has_one :profile
before_create :build_profile
has_many :friendships
has_many :friends, :through => :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user
has_one :company

acts_as_messageable

def name
	"User #{id}"
end

def mailboxer_email(object)
	nil
end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :job
    #validates_uniqueness_of :vote_id, scope: :user_id
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @user = current_user
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to :back, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_filter :authenticate_user!

  def index
    @user = current_user
    @post = Post.new
    @jobs = Job.order('created_at DESC')
    @activities = PublicActivity::Activity.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/finds_helper.rb
module FindsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= simple_form_for(@friendship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :friend_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h2>Following</h2>
<ul>
  <div class="row">
    <% for friendship in @user.friendships %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail" style="background-color:#F0F8FF;">
          <% unless friendship.friend.profile.avatar_url.nil? %>
         <img src="<%=friendship.friend.profile.avatar_url(:card)%>">
             <% else %>
               <img src="/assets/defaultprofile" height=150px width=150px>
             <% end %>
          <div class="caption" style="background-color:white;">
            <h3><%=friendship.friend.first_name + " " + friendship.friend.last_name%></h3>
            <p><%=friendship.friend.bio%></p>
            <p><a href="<%=user_path(friendship.friend)%>" class="btn btn-info" role="button">Profile</a></p>
            <%= link_to "Unfollow", friendship, :method => :delete %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</ul>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>