config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'jobs/indexall'

  resources :posts
  resources :companies
  resources :jobs do
      member do
          put 'like', to: "jobs#upvote"
          get 'like'
    end

end

  resources :conversations do
    resources :messages
  end
  resources :searches
  resources :finds
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :profiles

  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"

   get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"

   resources :resumes, only: [:index, :new, :create, :destroy]

   root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :name, :description, uniqueness: { scope: :name, message: "company already exists!" }
  validates :name, :description, presence: true
end

app/models/find.rb
class Find < ActiveRecord::Base
  def find_names
      users = User.all
      users = users.where(["first_name LIKE?",first_name]) if first_name.present?
      users = users.where(["last_name LIKE?",last_name]) if last_name.present?
      return users
    end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
    acts_as_votable
    acts_as_voter
    has_many :like, dependent: :destroy
    has_many :liked_users, through: :like, source: :user
	include PublicActivity::Model
	tracked

	def self.search(search)
			if search
				where(["company LIKE ?", "%#{search}%"])
			else
				all
			end
		end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
	include PublicActivity::Model
	tracked
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	##Image Uploading
	  mount_uploader :avatar, AvatarUploader

		belongs_to :user
    validates_associated :user

	def self.search(search)

			if search
				where(["occupation LIKE ?", "%#{search}%"])
			else
				all
			end
		end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   belongs_to :user
end

app/models/search.rb
class Search < ActiveRecord::Base


		def find_jobs
			
			jobs = Job.all

			jobs = jobs.where(["company LIKE?", company ]) if company.present?
			jobs = jobs.where(["title LIKE?", title  ]) if title.present?
			jobs = jobs.where(["description LIKE?", description ]) if description.present?

			return jobs
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
acts_as_voter
has_many :jobs
has_many :like, dependent: :destroy
has_many :liked_votes, through: :like, source: :jobs
has_many :posts
has_many :resumes
has_one :profile
before_create :build_profile
has_many :friendships
has_many :friends, :through => :friendships
has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
has_many :inverse_friends, :through => :inverse_friendships, :source => :user
has_one :company

acts_as_messageable

def name
	"User #{id}"
end

def mailboxer_email(object)
	nil
end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :job
    #validates_uniqueness_of :vote_id, scope: :user_id
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.order('created_at DESC')
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @jobs = User.find(@company.user_id).jobs.all
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_filter :authenticate_user!

  def index
    @user = current_user
    @post = Post.new
    @jobs = Job.order('created_at DESC')
    @activities = PublicActivity::Activity.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/finds_helper.rb
module FindsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <legend>Avatar</legend>
<%= f.file_field :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div style="background-color: white;">
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>
</div>

app/views/companies/index.html.erb
<head>
<style>
div.company {
    width: 70%;
    height: 200px;
    background-color: #d0e3ed;
    margin-left: 15%;
}



article {
    margin-left: 20%;
    padding: 1em;
    overflow: hidden;
    text-align: left;

}

.round {
   /*max-width: 200px;*/
   /*max-height: 200px;*/
   border-radius: 50%;
   position: center;
   margin-left: 40px;
   margin-top: -75px;
}

.round img {
  display: block;
  /* make a square container */
  min-width: 200px;
  min-height: 200px;
  /* fill the container, preserving aspect ratio, and cropping to fit */
  background-size: cover;
  /* center the image vertically and horizontally */
  background-position: center;
  /* round the edges to a circle with border radius 1/2 container size */
  border-radius: 50%;
  /*border*/
  border:1px solid gray;
}

.adv {
  float: right;
  margin-right:245px;
  margin-top:15px;
  overflow:hidden;
}

.search {
  position: absolute;
  float: left;
  margin-left: 165px;
  width: 50%;
  overflow:hidden;
}

.bluebox {
  margin-top:40px;
}

.description {
  position: absolute;
  margin-left: 120px;
  margin-right:300px;
  float: right;
  margin-top:-150px;
  font-size: 16px;
  left:25%;
}

</style>
</head>

<div style="background-color: clear;">

<!--
<div class="search">
-->

<!--
<div class="adv">
  <%= link_to "Advanced Search", new_search_path %>
</div>
-->

<!--  <%= link_to new_search_path, class: "adv", id: "id" do %>
   Advanced Search
<% end %>
-->


<!--<h1>Company</h1> -->
<h3> Listing Companies </h3>
<% if current_user.premium? && !(current_user.company)%>
<%= link_to 'New Company', new_company_path %>
  <%end%>
<table style="width:100%; border-collapse: separate; border-spacing: 0px 10px">
  <% @companies.each do |company| %>
    <tr>
      <td>
        <div class="bluebox">
        <div style="width:90%; height:250px; background-color: #d0e3ed; margin-left:5%; ">
          <header style="padding:1em; color:black; clear:left; text-align:center;">
            <a href="companies/<%=company.id%>">
            <h1><%= company.name %></h1>
          </a>
          </header>
          <div>
            <% unless company.avatar_url.nil? %>
              <div class="round">
                <%= image_tag(company.avatar_url(:profile), size:"200") %>
              </div>
              <% else %>
              <div class="round">
                <img src="/assets/defaultcompany">
              </div>
              <% end %>
              <div style="margin-left:10%;">
                <% if company.user_id == current_user.id %>
                <%= link_to 'Edit Company', edit_company_path(company) %>
                <% end %>
              </div>
          </div>
        </div>
        <div class="description">
            <%= company.description %>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>
</div>

<!--
<table style="width:100%; border-collapse: separate; border-spacing: 0px 10px">
  <thead style="font-size: 20px; border: 1px solid black">
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Description</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><% unless company.avatar_url.nil? %>
          <%= image_tag company.avatar_url(:profile) %>
          <% else %>
          <img src="/assets/defaultcompany" height=100px width=100px>
          <% end %>
          </td>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>



</div>

app/views/companies/new.html.erb
<div style="background-color: white;">
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<head>
<style>
div.company {
    width: 70%;
    height: 200px;
    background-color: #d0e3ed;
    margin-left: 15%;
}



article {
    margin-left: 20%;
    padding: 1em;
    overflow: hidden;
    text-align: left;

}

.round {
   /*max-width: 200px;*/
   /*max-height: 200px;*/
   border-radius: 50%;
   position: center;
   margin-left: 40px;
   margin-top: -75px;
}

.round img {
  display: block;
  /* make a square container */
  min-width: 200px;
  min-height: 200px;
  /* fill the container, preserving aspect ratio, and cropping to fit */
  background-size: cover;
  /* center the image vertically and horizontally */
  background-position: center;
  /* round the edges to a circle with border radius 1/2 container size */
  border-radius: 50%;
  /*border*/
  border:1px solid gray;
}

.adv {
  float: right;
  margin-right:245px;
  margin-top:15px;
  overflow:hidden;
}

.search {
  position: absolute;
  float: left;
  margin-left: 165px;
  width: 50%;
  overflow:hidden;
}

.bluebox {
  margin-top:40px;
}

.description {
  position: absolute;
  margin-left: 120px;
  margin-right:300px;
  float: right;
  margin-top:-150px;
  font-size: 16px;
  left:25%;
}

</style>
</head>
<p id="notice"><%= notice %></p>

    <div class="bluebox">
    <div style="width:90%; height:250px; background-color: #d0e3ed; margin-left:5%; ">
      <header style="padding:1em; color:black; clear:left; text-align:center;">

        <h1><%= @company.name %></h1>
      </a>
      </header>
    <div class="col-md-2">
        <% unless @company.avatar_url.nil? %>
          <div class="round">
            <%= image_tag(@company.avatar_url(:profile), size:"200") %>
          </div>
          <% else %>
          <div class="round">
            <img src="/assets/defaultcompany">
          </div>
          <% end %>
          <div style="margin-left:10%;">
            <% if @company.user_id == current_user.id %>
            <%= link_to 'Edit Company', edit_company_path(@company) %>
            <% end %>
          </div>
      </div>
    </div>
    <div class="description">
        <%= @company.description %>
      </div>
    </div>
<br>
<div class="col-sm-6 col-md-offset-3">
<h2> All Jobs </h2>
<% @jobs.each do |a| %>
<div id="jobbox" style="background-color:#F0F8FF; margin-bottom: 15px;">
  <h2 style="background-color: #F0F8FF;">
    <%= link_to a.company, job_path(a) %></h2>
  <div id="jobtitle" style="background-color: white;">
    <h6> Job Title </h6>
    <div style="border: solid 1px; height: 50px" >
      <%= a.title %>
    </div>
    <h6> Description </h6>
    <div style="border: solid 1px; height: 80px">
      <%= a.description %>
    </div>
    <%= link_to like_job_path(a), method: :put do%>
    Upvote
    <%= a.get_upvotes.size %>

    <% end %>
    </div>
    </div>
    <%end %>
</div>